### ISSUE TITLE
Create empty ManagedClusterInfo in 3-node base

### ISSUE THREAD

**Issue by natifridman** [redhat-partner-solutions/vse-ocp-bases#14]
`ManagedClusterInfo` is created by ACM behind the scene.
Argo CD keeps syncing this object, a possible solution is to create an empty object so Argo will know it.

**Comment by jnunyez** [comment]
See for inspiration  https://github.com/jnunyez/cluster-config/blob/bcc239ef0a6dc6d821076a4e5baf315e1014c9ba/manifests/workload-clusters/overlays/volante/09-mci.yaml

What I dont get from what you commented is how with ResourceExclusions does not work.
